version: '3.8'


services:
  pet-app:
    build: ./
    command: ./pet-app
    ports:
      - "8000:8000"
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres